export const cities = [
  { name: "Karachi", slug: "karachi" },
  { name: "Lahore", slug: "lahore" },
  { name: "Faisalabad", slug: "faisalabad" },
  { name: "Rawalpindi", slug: "rawalpindi" },
  { name: "Gujranwala", slug: "gujranwala" },
  { name: "Peshawar", slug: "peshawar" },
  { name: "Multan", slug: "multan" },
  { name: "Hyderabad", slug: "hyderabad" },
  { name: "Islamabad", slug: "islamabad" },
  { name: "Quetta", slug: "quetta" },
  { name: "Bahawalpur", slug: "bahawalpur" },
  { name: "Sargodha", slug: "sargodha" },
  { name: "Sialkot", slug: "sialkot" },
  { name: "Sukkur", slug: "sukkur" },
  { name: "Larkana", slug: "larkana" },
  { name: "Rahim Yar Khan", slug: "rahim-yar-khan" },
  { name: "Sheikhupura", slug: "sheikhupura" },
  { name: "Jhang", slug: "jhang" },
  { name: "Dera Ghazi Khan", slug: "dera-ghazi-khan" },
  { name: "Gujrat", slug: "gujrat" },
  { name: "Sahiwal", slug: "sahiwal" },
  { name: "Wah Cantonment", slug: "wah-cantonment" },
  { name: "Mardan", slug: "mardan" },
  { name: "Kasur", slug: "kasur" },
  { name: "Okara", slug: "okara" },
  { name: "Mingora", slug: "mingora" },
  { name: "Nawabshah", slug: "nawabshah" },
  { name: "Chiniot", slug: "chiniot" },
  { name: "Kotri", slug: "kotri" },
  { name: "Hafizabad", slug: "hafizabad" },
  { name: "Sadiqabad", slug: "sadiqabad" },
  { name: "Mirpur Khas", slug: "mirpur-khas" },
  { name: "Burewala", slug: "burewala" },
  { name: "Kohat", slug: "kohat" },
  { name: "Khanewal", slug: "khanewal" },
  { name: "Dera Ismail Khan", slug: "dera-ismail-khan" },
  { name: "Turbat", slug: "turbat" },
  { name: "Muzaffargarh", slug: "muzaffargarh" },
  { name: "Abbotabad", slug: "abbotabad" },
  { name: "Mandi Bahauddin", slug: "mandi-bahauddin" },
  { name: "Shikarpur", slug: "shikarpur" },
  { name: "Jacobabad", slug: "jacobabad" },
  { name: "Jhelum", slug: "jhelum" },
  { name: "Khanpur", slug: "khanpur" },
  { name: "Khairpur", slug: "khairpur" },
  { name: "Khuzdar", slug: "khuzdar" },
  { name: "Pakpattan", slug: "pakpattan" },
  { name: "Hub", slug: "hub" },
  { name: "Daska", slug: "daska" },
  { name: "Gojra", slug: "gojra" },
  { name: "Dadu", slug: "dadu" },
  { name: "Muridke", slug: "muridke" },
  { name: "Bahawalnagar", slug: "bahawalnagar" },
  { name: "Samundri", slug: "samundri" },
  { name: "Tando Allahyar", slug: "tando-allahyar" },
  { name: "Tando Adam", slug: "tando-adam" },
  { name: "Jaranwala", slug: "jaranwala" },
  { name: "Chishtian", slug: "chishtian" },
  { name: "Muzaffarabad", slug: "muzaffarabad" },
  { name: "Attock", slug: "attock" },
  { name: "Vehari", slug: "vehari" },
  { name: "Kot Abdul Malik", slug: "kot-abdul-malik" },
  { name: "Ferozwala", slug: "ferozwala" },
  { name: "Chakwal", slug: "chakwal" },
  { name: "Kamalia", slug: "kamalia" },
  { name: "Umerkot", slug: "umerkot" },
  { name: "Ahmedpur East", slug: "ahmedpur-east" },
  { name: "Kot Addu", slug: "kot-addu" },
  { name: "Wazirabad", slug: "wazirabad" },
  { name: "Mansehra", slug: "mansehra" },
  { name: "Layyah", slug: "layyah" },
  { name: "Mirpur", slug: "mirpur" },
  { name: "Swabi", slug: "swabi" },
  { name: "Chaman", slug: "chaman" },
  { name: "Taxila", slug: "taxila" },
  { name: "Nowshera", slug: "nowshera" },
  { name: "Khushab", slug: "khushab" },
  { name: "Shahdadkot", slug: "shahdadkot" },
  { name: "Talagang", slug: "talagang" },
  { name: "Kāmoke", slug: "kamoke" },
  { name: "Kabal", slug: "kabal" },
  { name: "Haroonabad", slug: "haroonabad" },
  { name: "Kamber Ali Khan", slug: "kamber-ali-khan" },
  { name: "Bhalwal", slug: "bhalwal" },
]
